name: 'Run Project Tests'
description: 'Github Action to run the project test code.'

inputs:
  main_path:
    required: true
  test_class:
    required: true

runs:
  using: "composite"
  steps:
  - name: Run Project Test Code
    id: run-test-code
    shell: bash
    working-directory: ${{ inputs.main_path }}
    run: |
      echo "Running Project Tests..."
      mvn -ntp -Dtest="${{ inputs.test_class }}*" test
